version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3 