# Generated by Django 4.2 on 2025-03-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("code", models.TextField()),
                ("language", models.CharField(default="python", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_in",
                    models.IntegerField(
                        choices=[(1, "1 Hour"), (24, "1 Day"), (168, "1 Week")],
                        default=24,
                    ),
                ),
                ("expiry_date", models.DateTimeField()),
            ],
            options={"ordering": ["-created_at"],},
        ),
    ]
